### ISSUE TITLE
Error occurs when trying to debug HS38 barebones app using openOCD

### ISSUE THREAD

**Issue by mellowcandle** [foss-for-synopsys-dwc-arc-processors/arc_gnu_eclipse#17]
The FPGA is AXS103 with HS38.
This is the error that I get.

Open On-Chip Debugger 0.9.0-dev-g8a252b3 (2015-06-08-13:44)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.sourceforge.net/doc/doxygen/bugs.html
debug_level: 0
adapter speed: 10000 kHz
target state: halted
target state: halted
Error: Unable to set 32bit breakpoint at address 20000078 - check that memory is read/writable
Error: Unable to set 32bit breakpoint at address 20000078 - check that memory is read/writable
Assertion failed!

Program: C:\arc_gnu\bin\openocd.exe
File: arc_mem.c, Line 34

Expression: addr_end >= addr

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by anthony-kolesov** [comment]
Hello Ramon,

That happens when you just debugging session and 0x20000078 is an address of main function, right? You don't do anything else? What's the application? Something trivial?

**Comment by mellowcandle** [comment]
Yes.  it's trivial.  compiled using makefile.
not through eclipse project.
Is there a way to provide you more logs?

**Comment by anthony-kolesov** [comment]
We'll try to reproduce locally first.

OpenOCD doens't really work HS38 on AXS103, because L2$ is not supported. However that shouldn't cause this particular error message, nor should it cause a failed assertion.

**Comment by mellowcandle** [comment]
Can I disable the l2 cache?

**Comment by anthony-kolesov** [comment]
No, as I have just found L2 cannot be disabled.

**Comment by pologovaa** [comment]
Hello Ramon,

I've tried to reproduce this error locally, and when I use old version of OpenOCD (same as you), I get an error, but it differs from yours. However, if I use OpenOCD from our 2015.12 RC1, there are no errors. In that case gdb loads, stops at a breakpoint and then if I try to continue or step it just stays at the same breakpoint. It is expected and happens because of L2 cache.

Could you try to debug your HS38 app using OpenOCD from 2015.12 RC1? If you saw the same as I do, it would mean that we've already fixed the problem you described.

**Comment by mellowcandle** [comment]
Of course. I will try tomorrow morning.
Thanks.
Ramon

**Comment by mellowcandle** [comment]
Is there a place where I can download a prebuilt release of that (Windows
64bit) ?

**Comment by anthony-kolesov** [comment]
Full installer for windows can be downloaded here: https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/releases/tag/arc-2015.12-rc1

If you want just an openOCD, standalone zip here: https://github.com/foss-for-synopsys-dwc-arc-processors/openocd/releases/tag/arc-2015.12-rc1
