### ISSUE TITLE
Build Project

### ISSUE THREAD

**Issue by ManuelAlfonso** [foss-for-synopsys-dwc-arc-processors/arc_gnu_eclipse#29]
Hi,
I want work with nSIM simulator, but for it I needed install eclipse with CDT, so, I am going to write the step that I followed:

1º Install Eclipse
2º Add cdt 8.8.0
3º Add Plugins
4º Add arc_gnu_201512_prebuilt_elf32_le_lnux_install.tar.gz
5º Create C project
        5.1 Project Type: "ARC Cross ELF32 Target Application"
        5.2 Toolchains: "GNU Toolchain for ARC EM"
6º Build Project

And here I have a error, eclipse tell me "recipe for target "/usr/helloARC.o" failed        subdir.mk"
Could somebody help me?

I have to say that also I tried on Windows and I had the same problem, but I resolved it installing cygwin, but on Ubuntu it's impossible.

Thank you very much.

**Comment by anthony-kolesov** [comment]
Have you tried with CDT 8.8? We don't really test compatibility with older CDT or Eclipse versions.

**Comment by ManuelAlfonso** [comment]
I use Eclipse Luna but really it's the same and I downloaded the cdt 8.8.0 and 8.8.1

**Comment by anthony-kolesov** [comment]
It seems to work for me. Is there any text preceding  "recipe for target "/usr/helloARC.o" failed subdir.mk"?

**Comment by ManuelAlfonso** [comment]
No, nothing, look.
![imagen](https://cloud.githubusercontent.com/assets/20947994/18351123/32d75460-75d9-11e6-9c23-35ec7a8a3618.png)

where say "fallo en las instrucciones para el objetivo ...." is the error. but eclipse say me in spanish.

**Comment by anthony-kolesov** [comment]
What is in the "Console" window?

**Comment by ManuelAlfonso** [comment]
![imagen2](https://cloud.githubusercontent.com/assets/20947994/18351441/7c36faa6-75da-11e6-999a-28bf209f6756.png)

**Comment by anthony-kolesov** [comment]
Plugin version 2015.12 cannot generate -mcpu=em. Are use using a TCF file?

**Comment by ManuelAlfonso** [comment]
Ok, look, I have changed in the setting build, in ARC EM I have put -mcpy=arcem and then I have another error that say "cc1" doesn't found, so, I added this file in the folder /bin and now I have this:

![imagen3](https://cloud.githubusercontent.com/assets/20947994/18352631/71038f78-75df-11e6-9d03-0562fd09cb33.png)

**Comment by anthony-kolesov** [comment]
It is not right that arc-elf32-gcc cannot find cc1. Are there "libexec" and "share" folders that are the siblings of "bin"?

**Comment by ManuelAlfonso** [comment]
Yes, look:
![imagen4](https://cloud.githubusercontent.com/assets/20947994/18352900/88f382fe-75e0-11e6-9f7b-56cebe14f9d9.png)

**Comment by anthony-kolesov** [comment]
Are you sure that this "bin" folder is the one in the PATH? Can you try compiling something simple with bin/arc-elf32-gcc manually from command line without Eclipse? Would it work? Also remove cc1 from bin folder - it should be in libexec/gcc/arc-elf32/4.8.5, if it is in the bin folder it would just obscure the real problem.

**Comment by ManuelAlfonso** [comment]
![imagen5](https://cloud.githubusercontent.com/assets/20947994/18353433/3db82e96-75e2-11e6-857b-1ccaed63030a.png)

This is if I compile manually.
The other thing that you say about cc1. 
I have this:


![imagen4](https://cloud.githubusercontent.com/assets/20947994/18353474/62f8f01e-75e2-11e6-9506-29e9b52b8a35.png)

And in this folder bin, I don't have the cc1 file. The cc1 file I found in  ./libexec/gcc/arc-elf32/4.8.5 there, so, I did, when I was in this folder (./libexec/gcc/arc-elf32/4.8.5) I did, "cp * /bin" and here (./libexec/gcc/arc-elf32/4.8.5) I have this:

![imagen6](https://cloud.githubusercontent.com/assets/20947994/18353579/d32beb02-75e2-11e6-81b5-f057111b2568.png)
so, I moved all this file to folder /bin

**Comment by anthony-kolesov** [comment]
> so, I moved all this file to folder /bin

Please revert this action and retry with compiling manually.

**Comment by ManuelAlfonso** [comment]
I have done this: (I remove exactly this file that I had moved to /bin)
And now I have compiled manually:

![imagen7](https://cloud.githubusercontent.com/assets/20947994/18353901/093ddf24-75e4-11e6-890d-6167604c83bb.png)

**Comment by anthony-kolesov** [comment]
Is there a reason why you run as root and toolchain is right in the root folder - /bin/arc-elf32-gcc?

**Comment by ManuelAlfonso** [comment]
Don't but, i try again without root and i have the same problem.

**Comment by ManuelAlfonso** [comment]
I have to say that from this folder
![imagen4](https://cloud.githubusercontent.com/assets/20947994/18355466/72a8a61a-75e9-11e6-85c3-df6371a84332.png)

I moved the folder bin, and the folder bin that this was in the folder arc-elf32 that you can see in the image. Maibe it is also a problem..

**Comment by anthony-kolesov** [comment]
So you have moved "bin" from arc_gnu_2015.12_prebuilt_elf32_le_linux_install to /? That is the problem I think. You should be calling the arc-elf32-gcc that is the arc_gnu_2015.12_prebuilt_elf32_le_linux_install/bin/arc-elf32-gcc - right from the folder where it is located. It searches for cc1 relatively to it's location, so copying just "bin" doesn't work.

**Comment by ManuelAlfonso** [comment]
I moved bin from arc_gnu_2015.12_prebuilt_elf32_le_linux_install to /bin (this is the first imagen in the last answer)
and
I moved bin from arc_gnu_2015.12_prebuilt_elf32_le_linux_install/arc-elf32 to /bin (this is the last image)

so, I remove from /bin the files from bin (bin from arc_gnu_2015.12_prebuilt_elf32_le_linux_install/arc-elf32)?? 

or what do I do now?

**Comment by anthony-kolesov** [comment]
I think you should remove files that you moved, in case they would cause any problem for other tools.

To compile you should be invoking `~/Downloads/arc_gnu_2015.12_prebuilt_elf32_le_linux_install/bin/arc-elf32-gcc`.

**Comment by ManuelAlfonso** [comment]
Ok, I'm going to try but, the thing is, I moved it because in eclipse when I was going to create a C project and I needed say the project type the "ARC Cross ELF32 Target" doesn't recognized.

**Comment by anthony-kolesov** [comment]
You should add `~/Downloads/arc_gnu_2015.12_prebuilt_elf32_le_linux_install/bin` to the PATH - then Eclipse will find compiler.

**Comment by ManuelAlfonso** [comment]
Eclipse have a different PATH to the system PATH? Because I added this the first time, but it didn't work I moved the files.

**Comment by ManuelAlfonso** [comment]
I did that, but nothing, I don't understand why there are a lot problems.
![image9](https://cloud.githubusercontent.com/assets/20947994/18356791/8add3f20-75ee-11e6-987a-4d7c8e664449.png)

**Comment by ManuelAlfonso** [comment]
I have to say that I added this folder bin to PATH, modifying the file ~/.bashrc and I put this:  PATH=”$PATH:/folder" and this folder after was added but, Eclipse doesn't recognized I talk about PATH system, I don't know if eclipse have another PATH.

**Comment by anthony-kolesov** [comment]
To resolve the problem with undefined symbols, you need to add `--specs=nsim.specs` option (https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/wiki/Building-a-baremetal-application).

Eclipse uses normal PATH. Before running Eclipse, have you started a new bash terminal after modifying bashrc, so it would grab the modifed PATH? Have you checked that PATH indeed contains proper path to arc-elf32-gcc before running Eclipse?

**Comment by ManuelAlfonso** [comment]
Ok, this evening I will try. I will tell you something.

Thank you very much.

**Comment by ManuelAlfonso** [comment]
I have done everything from the beginning.
Now, I just added the folder in the PATH, look
![image10](https://cloud.githubusercontent.com/assets/20947994/18365679/f5bd36b8-7613-11e6-97be-556949045469.png)

I have closed the terminal, and I have open again and everything is correct.

I open eclipse, and look:

![image11](https://cloud.githubusercontent.com/assets/20947994/18365734/269089a2-7614-11e6-8897-766559346a1a.png)

Eclipse doesn't recognize "ARC Cross..." 
so I have done this: Windows -> Preferences -> C/C++ -> Build and in Build Variables and environment I have added the PATH. but nothing.

**Comment by ManuelAlfonso** [comment]
Hi again,

I tried start eclipse in terminal, and now, work perfect., well, rather, build perfect. The other things i don't know for now.

Thank you, for everything.

**Comment by ManuelAlfonso** [comment]
One thing, I have tried debbug, and in Debbug configurations, 
![image11](https://cloud.githubusercontent.com/assets/20947994/18380602/608700f0-7678-11e6-98f6-0d162f42a424.png)

And when I apply and Debug, I have a error, this error:

![imagen12](https://cloud.githubusercontent.com/assets/20947994/18380643/8ed95b2e-7678-11e6-9f21-943565182d22.png)

But, really it exits, so..
![image13](https://cloud.githubusercontent.com/assets/20947994/18380658/a94d136a-7678-11e6-9394-ea6e2e010ce3.png)

Why do I have this error?

**Comment by ManuelAlfonso** [comment]
Finally it work perfect, I needed the file /libe?ld-linuex.so.2 .
Strange error.
But OK, All is perfect.

**Comment by ManuelAlfonso** [comment]
Hi Anton,

First, sorry for inconveniences.
One more thing, where have I put "--specs=nsim.specs" that you told me?

Thank you very much

Quoting Anton Kolesov <notifications@github.com>:

> To resolve the problem with undefined symbols, you need to add
> --specs=nsim.specs option
>
(https://github.com/foss-for-synopsys-dwc-arc-processors/toolchain/wiki/Building-a-baremetal-application).
>
>   Eclipse uses normal PATH. Before running Eclipse, have you started a
> new bash terminal after modifying bashrc, so it would grab the modifed
> PATH? Have you checked that PATH indeed contains proper path to
> arc-elf32-gcc before running Eclipse?
>
>   —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[1], or mute the
thread[2].
>       



Links:
------
[1]  
https://github.com/foss-for-synopsys-dwc-arc-processors/arc_gnu_eclipse/issues/29#issuecomment-245651228
[2]

**Comment by anthony-kolesov** [comment]
Project settings, C/C++ Build, Settings, Linker, Misc, Other flags.
![untitled](https://cloud.githubusercontent.com/assets/602123/18385986/79e7ff4e-769c-11e6-9d75-e9ab4775ac54.png)

**Comment by ManuelAlfonso** [comment]
I have done this but it doesn't work, maibe I am doing something wrong:

![imagen20](https://cloud.githubusercontent.com/assets/20947994/18386136/28a83056-7695-11e6-85bf-2a0d23f9a3d7.png)

And after Build:

![imagen21](https://cloud.githubusercontent.com/assets/20947994/18386145/35eceb08-7695-11e6-9e4f-65ef85b9cff4.png)

Where say "fallo en las instrucciones para el objetivo" is -> recipe for target failed.

**Comment by anthony-kolesov** [comment]
Options in Other flags should be separated by the whitespace, not by semicolon. Although it seems like there is a bug, that modifying this fields breaks project building - you may need to just create project from the scratch if that will happen.

**Comment by ManuelAlfonso** [comment]
Ok, I have corrected this:
![imagen30](https://cloud.githubusercontent.com/assets/20947994/18386528/fd0e8bf4-7697-11e6-897b-80c97dc08310.png)

![imagen31](https://cloud.githubusercontent.com/assets/20947994/18386533/0110fdea-7698-11e6-93ae-ad740fb92a17.png)

But I have problems:

![imagen33](https://cloud.githubusercontent.com/assets/20947994/18386552/118822e8-7698-11e6-9ecf-a4d07a4c0ef9.png)

where say "primero se definió aquí" it's mean "first it's defined here".

It's impossible that I have a lot of problems.

**Comment by ManuelAlfonso** [comment]
I have deleted "--specs=nsim.specs" in Compiler - Mis, so, now, I have this:

![imagen40](https://cloud.githubusercontent.com/assets/20947994/18387546/8c71090c-769d-11e6-96b9-b35eb0fef23e.png)


![imagen41](https://cloud.githubusercontent.com/assets/20947994/18387549/904f6df2-769d-11e6-9eaf-dd73ed0f628c.png)


And I have this error.

![imagen42](https://cloud.githubusercontent.com/assets/20947994/18387593/b6fab6be-769d-11e6-9f90-964a4d9a4bb2.png)

**Comment by ManuelAlfonso** [comment]
Everything I think is correct.

Thank you very much.
