### ISSUE TITLE
Searching tools in PATH does not work

### ISSUE THREAD

**Issue by spb-yuriy** [foss-for-synopsys-dwc-arc-processors/arc_gnu_eclipse#3]
It seems like Eclipse can't find tools in `PATH` if they are not presented in Eclipse's `bin` directory. Bug is introduced in this commit: https://github.com/foss-for-synopsys-dwc-arc-processors/arc_gnu_eclipse/commit/7763a8f0cbed20ee20574a0c98c4e691e132cc6d. `IsToolChainSupported.java` always appends predefined path to the tool command. Is it an issue or an expected behavior?

**Comment by anthony-kolesov** [comment]
Perhaps you should have put here an explanation why it is "invalid".

**Comment by spb-yuriy** [comment]
I've considered that creating of issue is redundant since I've already introduced a patch and going to create a Pull Request.

**Comment by anthony-kolesov** [comment]
That would be ok if there was no Issue in the first place. But since you already opened it, better way is to mention in pull request that it fixes Issue #3. And definitely the reason of closure would be not "invalid".

**Comment by anthony-kolesov** [comment]
Pull request has been merged.
