### ISSUE TITLE
Request for fix the picture loss in Wiki

### ISSUE THREAD

**Issue by willtuna** [foss-for-synopsys-dwc-arc-processors/arc_gnu_eclipse#58]
Hello, could you please make up the picture loss in the plug-in installation tutorial for 2017.09version ?
https://github.com/foss-for-synopsys-dwc-arc-processors/arc_gnu_eclipse/wiki/Installation#4-updating-existing-plugin

**Comment by anthony-kolesov** [comment]
Hi, thanks for the report!

I fixed links to images, but I recommend using our new documentation site at https://embarc.org/toolchain/ide/installation.html

**Comment by willtuna** [comment]
Thanks for your response...
