### ISSUE TITLE
How to run my own project on arc_gnu_eclipse?

### ISSUE THREAD

**Issue by L-leopold** [foss-for-synopsys-dwc-arc-processors/arc_gnu_eclipse#68]
Hello!
I want to run my own project with my own makefile  in the eclipse.
So,I choose the Makefile project with existing code option.
But I didn't find any settings to set my hsdk board configuration，like FPU ,or ARC HS（-mcpu) and so on.
Usually ,the settings is in the properties, but it does not seem like other program setting,which sets the target processor(-mcpu) to set up the environment to run in.
Sorry, I didn't find any courses or examples about teaching how to run own makefile and code .
I want to ask how to run my own makefile and my own code in the eclipse
I do not know whether you see what I mean .If you do not get my point ,please reply to me and let me explain more specifically.
Thank you.

**Comment by anthony-kolesov** [comment]
Hi,

If you want to run with your own Makefile then you have to specify your compiler options in the Makefile itself - there is no support for custom Makefiles, those plugins support only Eclipse-generated projects. You still can use a hello-world example projects to configure CPU, and copy-paste GCC invocation line from the Settings into your Makefile.

**Comment by L-leopold** [comment]
Thank  you sir 
I studied osp's makefile deeply and changed the internal compilation settings，I will do my best to fix it
